name: Nightly
on:  
  push:    
    branches:      
      - developer    
    paths:      
      - '.github/workflows/main.yaml'      
      - 'src/**'      
      - 'deps/**'      
      - 'pom.xml'  
  workflow_dispatch:

jobs:  
  build:    
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v4      
      
      - name: Set up JDK 8        
        uses: actions/setup-java@v4.6.0        
        with:          
          java-version: '8'          
          distribution: 'corretto'      
          
      - name: Set up maven        
        uses: s4u/setup-maven-action@v1.18.0        
        with:          
          java-version: '8'      
          
      - name: Clone Repository        
        run: git clone --branch developer --recursive https://github.com/NTifyApp/NTify      
        
      - name: Get commit ID        
        id: get_commit_id        
        run: echo "COMMIT_ID=${GITHUB_SHA}" >> "$GITHUB_OUTPUT"      
        
      - name: Save commit ID to file        
        working-directory: ./NTify        
        run: echo ${{ steps.get_commit_id.outputs.COMMIT_ID }} > src/main/resources/commit_id.txt      
        
      - name: Build with Maven and build.py        
        working-directory: ./NTify        
        run: python3 build.py      
        
      - name: Upload a Build Artifact        
        uses: actions/upload-artifact@v4.6.0        
        with:          
          name: Build          
          path: NTify/target/NTify.jar
          
      - name: Get commit info        
        id: commit        
        run: |          
          echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV          
          echo "title=$(git log -1 --pretty=format:%s)" >> $GITHUB_ENV          
          echo "message<<EOF" >> $GITHUB_ENV          
          git log -1 --pretty=format:%b >> $GITHUB_ENV          
          echo "EOF" >> $GITHUB_ENV      
          
      - name: Creating release        
        uses: softprops/action-gh-release@v2        
        env:          
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
        with:          
          tag_name: ${{ env.sha }}          
          name: ${{ env.title }}          
          files: NTify/target/NTify.jar
          draft: 'false'          
          prerelease: 'false'      
          
      - name: Make public directory        
        working-directory: ./NTify        
        run: mkdir public      
        
      - name: Copy app screenshot to public directory        
        working-directory: ./NTify        
        run: cp NTifyShowStable.png public/      
        
      - name: Copy newest release to public directory        
        working-directory: ./NTify        
        run: cp target/NTify.jar public/
        
      - name: Copy release title to public directory        
        working-directory: ./NTify        
        run: echo ${{ env.title }} > public/commit_title.txt      
        
      - name: Copy release message to public directory        
        working-directory: ./NTify        
        run: echo '${{ env.message }}' > public/commit_message.txt      
        
      - name: Upload to GitHub Pages        
        uses: peaceiris/actions-gh-pages@v4        
        with:          
          github_token: ${{ secrets.GITHUB_TOKEN }}          
          publish_dir: ./NTify/public
